os: linux
dist: focals

branches:
  only:
  - main

services:
- docker

install:
- sudo snap install kubectl --classic
- mkdir -vp ~/.docker/cli-plugins/
- curl --silent -L "https://github.com/docker/buildx/releases/download/v0.7.0/buildx-v0.7.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
- chmod a+x ~/.docker/cli-plugins/docker-buildx

script: ./build.sh $TRAVIS_COMMIT_MESSAGE

before_deploy:
- mkdir ${HOME}/.kube
- echo "$KUBECONFIG_ENC" | base64 --decode > ${HOME}/.kube/config
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh $TRAVIS_COMMIT_MESSAGE
  on:
    branch: main
